
package cgtcalc.json_Tools;

/**
 *
 * @author mat
 */
public class Configuration {
    private String transactionFile;
    private String openingPositionsFile;
    private String closingPositionsFile;
    private String htmlReportFile;
    private String modsFile;
    private int calculationMethod;
    
    public Configuration() {
        
    }
    
    /**
     * A Configuration object holding all the different file names and processing methods.
     * @param transactionFile The file from HL with no changes, so you can leave the big header.
     * @param openingPositionsFile The file generated by this tool as closing positions 
     * from the previous year.
     * @param closingPositionsFile The closing positions from the year which is information
     * about the stocks purchased, along with the price that they were purchased at
     * @param htmlReportFile This is the generated output file in HTML format with
     * navigation within it
     * @param modsFile Manual modifications that are added to solve things like share 
     * splits and rights issues where HL don't provide enough information in their file.
     * This is the exact same format as a transactionFile (with the same header) and
     * the same function is used to read it.  Note that transactions should have a number 
     * of 0 as this is looked for in the code.
     * @param calculationMethod A method to do the calculations.  Method 1 is what
     * was originally used, but is wrong. You should use method 2 unless you really
     * need to use method 1.
     */
    public Configuration(String transactionFile, String openingPositionsFile, 
            String closingPositionsFile, String htmlReportFile, String modsFile,
            int calculationMethod) {
        this.transactionFile = transactionFile;
        this.openingPositionsFile = openingPositionsFile;
        this.closingPositionsFile = closingPositionsFile;
        this.htmlReportFile = htmlReportFile;
        this.modsFile = modsFile;
        this.calculationMethod = calculationMethod;
    }
    
    /**
     * A Configuration object holding all the different file names and processing methods.  This assumes
     * calculation method 2 which should be the default.
     * @param transactionFile The file from HL with no changes, so you can leave the big header.
     * @param openingPositionsFile The file generated by this tool as closing positions 
     * from the previous year.
     * @param closingPositionsFile The closing positions from the year which is information
     * about the stocks purchased, along with the price that they were purchased at
     * @param htmlReportFile This is the generated output file in HTML format with
     * navigation within it
     * @param modsFile Manual modifications that are added to solve things like share 
     * splits and rights issues where HL don't provide enough information in their file.
     * This is the exact same format as a transactionFile (with the same header) and
     * the same function is used to read it.  Note that transactions should have a number 
     * of 0 as this is looked for in the code.
     * 
     */
    public Configuration(String transactionFile, String openingPositionsFile, 
            String closingPositionsFile, String htmlReportFile, String modsFile) {
        this(transactionFile, openingPositionsFile, closingPositionsFile, htmlReportFile, modsFile, 2);
    }

    /**
     * @return the transactionFile
     */
    public String getTransactionFile() {
        return transactionFile;
    }

    /**
     * @return the openingPositionsFile
     */
    public String getOpeningPositionsFile() {
        return openingPositionsFile;
    }

    /**
     * @return the closingPositionsFile
     */
    public String getClosingPositionsFile() {
        return closingPositionsFile;
    }

    /**
     * @return the htmlReportFile
     */
    public String getHtmlReportFile() {
        return htmlReportFile;
    }

    /**
     * @return the modsFile
     */
    public String getModsFile() {
        return modsFile;
    }
    
    public int getCalculationMethod() {
        return calculationMethod;
    }
    
}
